CREATE EXTENSION IF NOT EXISTS pgcrypto;

CREATE TABLE IF NOT EXISTS users (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), full_name text, phone_normalized text UNIQUE NOT NULL, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS institutions (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), name text NOT NULL, slug text UNIQUE NOT NULL, logo_url text, description text, status text NOT NULL DEFAULT 'active', created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS institution_members (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), institution_id uuid NOT NULL REFERENCES institutions(id) ON DELETE CASCADE, user_id uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE, source text, status text NOT NULL DEFAULT 'active', created_at timestamptz NOT NULL DEFAULT now(), UNIQUE(institution_id, user_id));
CREATE TABLE IF NOT EXISTS user_institution_preferences (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), user_id uuid NOT NULL UNIQUE REFERENCES users(id) ON DELETE CASCADE, current_institution_id uuid REFERENCES institutions(id) ON DELETE SET NULL, origin_institution_id uuid REFERENCES institutions(id) ON DELETE SET NULL, updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS user_communication_preferences (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), user_id uuid NOT NULL UNIQUE REFERENCES users(id) ON DELETE CASCADE, whatsapp_operational_enabled boolean NOT NULL DEFAULT true, whatsapp_marketing_enabled boolean NOT NULL DEFAULT true, unsubscribed_marketing_at timestamptz, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS whatsapp_messages (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), user_id uuid REFERENCES users(id) ON DELETE SET NULL, phone_normalized text NOT NULL, direction text NOT NULL CHECK (direction IN ('inbound','outbound')), content text, message_type text NOT NULL DEFAULT 'text', intent text, external_message_id text, status text NOT NULL DEFAULT 'received', raw_payload jsonb, created_at timestamptz NOT NULL DEFAULT now());
CREATE INDEX IF NOT EXISTS idx_wm_user_id   ON whatsapp_messages(user_id);
CREATE INDEX IF NOT EXISTS idx_wm_phone     ON whatsapp_messages(phone_normalized);
CREATE INDEX IF NOT EXISTS idx_wm_ext_id    ON whatsapp_messages(external_message_id);
CREATE INDEX IF NOT EXISTS idx_wm_created   ON whatsapp_messages(created_at);
CREATE TABLE IF NOT EXISTS bot_sessions (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), user_id uuid NOT NULL UNIQUE REFERENCES users(id) ON DELETE CASCADE, current_state text NOT NULL DEFAULT 'idle', context jsonb NOT NULL DEFAULT '{}'::jsonb, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS bot_events (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), user_id uuid REFERENCES users(id) ON DELETE SET NULL, phone_normalized text NOT NULL, event_type text NOT NULL, intent text, current_state text, details jsonb DEFAULT '{}'::jsonb, created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS partner_stores (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), name text NOT NULL, domain text NOT NULL UNIQUE, status text NOT NULL DEFAULT 'active', supports_deeplink boolean NOT NULL DEFAULT true, created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS generated_links (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), user_id uuid REFERENCES users(id) ON DELETE SET NULL, institution_id uuid REFERENCES institutions(id) ON DELETE SET NULL, partner_store_id uuid REFERENCES partner_stores(id) ON DELETE SET NULL, original_url text NOT NULL, affiliate_url text, tracking_code text UNIQUE NOT NULL, short_url text, status text NOT NULL DEFAULT 'active', created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS link_clicks (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), generated_link_id uuid REFERENCES generated_links(id) ON DELETE CASCADE, user_id uuid REFERENCES users(id) ON DELETE SET NULL, institution_id uuid REFERENCES institutions(id) ON DELETE SET NULL, ip_address text, user_agent text, clicked_at timestamptz NOT NULL DEFAULT now());

INSERT INTO institutions (name, slug, status) VALUES ('Visão Mundial','visao-mundial','active'),('Amor de Bicho','amor-de-bicho','active') ON CONFLICT (slug) DO NOTHING;
INSERT INTO partner_stores (name, domain, status) VALUES ('Amazon','amazon.com.br','active'),('Shopee','shopee.com.br','active'),('Magalu','magazineluiza.com.br','active'),('Mercado Livre','mercadolivre.com.br','active') ON CONFLICT (domain) DO NOTHING;
